apiVersion: networking.controller/v1
kind: Gateway
metadata:
  name: test
spec:
  selector:
    app: test
  servers:
  - port:
      number: 443
  hosts:
  tls:
    mode: mutual
    credential: mypassword
    minProtocolVersion: TLSV1_1
